/**
 * xquery是一套小程序的开发工具库
 * 说明: 在小程序中搜索 xquery，更多demo和说明
 * 源码: https://github.com/webkixi/aotoo-xquery
 * 小程序代码片段: https://developers.weixin.qq.com/s/KSoWN2mE7Lem
 */
const Pager = require('../../components/aotoo/core/index')
let mkTab = require('../modules/indexlist')
const mockData = [
  {title: '好好学习', itemStyle: 'height: 80px'},
  {idf: 'A', title: 'A'},
  {
    img: {src: '/images/xquery.png', mode: 'widthFix'}, 
    title: '选项-1', 
    parent: "A"
  },
  {title: '选项-1', parent: "A"},
  {title: '选项-1', parent: "A"},
  {title: '选项-1', parent: "A"},
  {title: '选项-1', parent: "A"},
  {title: '选项-1', parent: "A"},
  {title: '选项-1', parent: "A"},
  {title: '选项-1', parent: "A"},
  {title: '选项-1', parent: "A"},
  {title: '选项-1', parent: "A"},
  {title: '选项-1', parent: "A"},
  {title: '选项-1', parent: "A"},
  {title: '选项-1', parent: "A"},
  {title: '选项-1', parent: "A"},
  {title: '选项-1', parent: "A"},
  {idf: 'B', title: 'B'},
  {title: '选项-2', parent: "B"},
  {title: '选项-2', parent: "B"},
  {title: '选项-2', parent: "B"},
  {title: '选项-2', parent: "B"},
  {title: '选项-2', parent: "B"},
  {title: '选项-2', parent: "B"},
  {title: '选项-2', parent: "B"},
  {title: '选项-2', parent: "B"},
  {title: '选项-2', parent: "B"},
  {title: '选项-2', parent: "B"},
  {title: '选项-2', parent: "B"},
  {title: '选项-2', parent: "B"},
  {idf: 'C', title: 'C'},
  {title: '选项-2', parent: "C"},
  {title: '选项-2', parent: "C"},
  {title: '选项-2', parent: "C"},
  {title: '选项-2', parent: "C"},
  {title: '选项-2', parent: "C"},
  {title: '选项-2', parent: "C"},
  {title: '选项-2', parent: "C"},
  {title: '选项-2', parent: "C"},
  {title: '选项-2', parent: "C"},
  {title: '选项-2', parent: "C"},
  {title: '选项-2', parent: "C"},
  {title: '选项-2', parent: "C"},
  // {idf: 'D', title: 'D'},
  // {title: '选项-2', parent: "D"},
  // {title: '选项-2', parent: "D"},
  // {title: '选项-2', parent: "D"},
  // {title: '选项-2', parent: "D"},
  // {title: '选项-2', parent: "D"},
  // {title: '选项-2', parent: "D"},
  // {title: '选项-2', parent: "D"},
  // {title: '选项-2', parent: "D"},
  // {title: '选项-2', parent: "D"},
  // {title: '选项-2', parent: "D"},
  // {title: '选项-2', parent: "D"},
  // {title: '选项-2', parent: "D"},
  // {idf: 'E', title: 'E'},
  // {title: '选项-2', parent: "E"},
  // {title: '选项-2', parent: "E"},
  // {title: '选项-2', parent: "E"},
  // {title: '选项-2', parent: "E"},
  // {title: '选项-2', parent: "E"},
  // {title: '选项-2', parent: "E"},
  // {title: '选项-2', parent: "E"},
  // {title: '选项-2', parent: "E"},
  // {title: '选项-2', parent: "E"},
  // {title: '选项-2', parent: "E"},
  // {title: '选项-2', parent: "E"},
  // {title: '选项-2', parent: "E"},
  // {idf: 'F', title: 'F'},
  // {title: '选项-2', parent: "F"},
  // {title: '选项-2', parent: "F"},
  // {title: '选项-2', parent: "F"},
  // {title: '选项-2', parent: "F"},
  // {title: '选项-2', parent: "F"},
  // {title: '选项-2', parent: "F"},
  // {title: '选项-2', parent: "F"},
  // {title: '选项-2', parent: "F"},
  // {title: '选项-2', parent: "F"},
  // {title: '选项-2', parent: "F"},
  // {title: '选项-2', parent: "F"},
  // {title: '选项-2', parent: "F"},
  // {idf: 'G', title: 'G'},
  // {title: '选项-2', parent: "G"},
  // {title: '选项-2', parent: "G"},
  // {title: '选项-2', parent: "G"},
  // {title: '选项-2', parent: "G"},
  // {title: '选项-2', parent: "G"},
  // {title: '选项-2', parent: "G"},
  // {title: '选项-2', parent: "G"},
  // {title: '选项-2', parent: "G"},
  // {title: '选项-2', parent: "G"},
  // {title: '选项-2', parent: "G"},
  // {title: '选项-2', parent: "G"},
  // {title: '选项-2', parent: "G"},
  // {idf: 'H', title: 'H'},
  // {title: '选项-2', parent: "H"},
  // {title: '选项-2', parent: "H"},
  // {title: '选项-2', parent: "H"},
  // {title: '选项-2', parent: "H"},
  // {title: '选项-2', parent: "H"},
  // {title: '选项-2', parent: "H"},
  // {title: '选项-2', parent: "H"},
  // {title: '选项-2', parent: "H"},
  // {title: '选项-2', parent: "H"},
  // {title: '选项-2', parent: "H"},
  // {title: '选项-2', parent: "H"},
  // {title: '选项-2', parent: "H"},
  // {idf: 'I', title: 'I'},
  // {title: '选项-2', parent: "I"},
  // {title: '选项-2', parent: "I"},
  // {title: '选项-2', parent: "I"},
  // {title: '选项-2', parent: "I"},
  // {title: '选项-2', parent: "I"},
  // {title: '选项-2', parent: "I"},
  // {title: '选项-2', parent: "I"},
  // {title: '选项-2', parent: "I"},
  // {title: '选项-2', parent: "I"},
  // {title: '选项-2', parent: "I"},
  // {title: '选项-2', parent: "I"},
  // {title: '选项-2', parent: "I"},
  // {idf: 'J', title: 'J'},
  // {title: '选项-2', parent: "J"},
  // {title: '选项-2', parent: "J"},
  // {title: '选项-2', parent: "J"},
  // {title: '选项-2', parent: "J"},
  // {title: '选项-2', parent: "J"},
  // {title: '选项-2', parent: "J"},
  // {title: '选项-2', parent: "J"},
  // {title: '选项-2', parent: "J"},
  // {title: '选项-2', parent: "J"},
  // {title: '选项-2', parent: "J"},
  // {title: '选项-2', parent: "J"},
  // {title: '选项-2', parent: "J"},
  // {idf: 'K', title: 'K'},
  // {title: '选项-2', parent: "K"},
  // {title: '选项-2', parent: "K"},
  // {title: '选项-2', parent: "K"},
  // {title: '选项-2', parent: "K"},
  // {title: '选项-2', parent: "K"},
  // {title: '选项-2', parent: "K"},
  // {title: '选项-2', parent: "K"},
  // {title: '选项-2', parent: "K"},
  // {title: '选项-2', parent: "K"},
  // {title: '选项-2', parent: "K"},
  // {title: '选项-2', parent: "K"},
  // {title: '选项-2', parent: "K"},
  // {idf: 'M', title: 'M'},
  // {title: '选项-2', parent: "M"},
  // {title: '选项-2', parent: "M"},
  // {title: '选项-2', parent: "M"},
  // {title: '选项-2', parent: "M"},
  // {title: '选项-2', parent: "M"},
  // {title: '选项-2', parent: "M"},
  // {title: '选项-2', parent: "M"},
  // {title: '选项-2', parent: "M"},
  // {title: '选项-2', parent: "M"},
  // {title: '选项-2', parent: "M"},
  // {title: '选项-2', parent: "M"},
  // {title: '选项-2', parent: "M"},
  // {idf: 'L', title: 'L'},
  // {title: '选项-2', parent: "L"},
  // {title: '选项-2', parent: "L"},
  // {title: '选项-2', parent: "L"},
  // {title: '选项-2', parent: "L"},
  // {title: '选项-2', parent: "L"},
  // {title: '选项-2', parent: "L"},
  // {title: '选项-2', parent: "L"},
  // {title: '选项-2', parent: "L"},
  // {title: '选项-2', parent: "L"},
  // {title: '选项-2', parent: "L"},
  // {title: '选项-2', parent: "L"},
  // {title: '选项-2', parent: "L"},
  // {idf: 'N', title: 'N'},
  // {title: '选项-2', parent: "N"},
  // {title: '选项-2', parent: "N"},
  // {title: '选项-2', parent: "N"},
  // {title: '选项-2', parent: "N"},
  // {title: '选项-2', parent: "N"},
  // {title: '选项-2', parent: "N"},
  // {title: '选项-2', parent: "N"},
  // {title: '选项-2', parent: "N"},
  // {title: '选项-2', parent: "N"},
  // {title: '选项-2', parent: "N"},
  // {title: '选项-2', parent: "N"},
  // {title: '选项-2', parent: "N"},
  // {idf: 'O', title: 'O'},
  // {title: '选项-2', parent: "O"},
  // {title: '选项-2', parent: "O"},
  // {title: '选项-2', parent: "O"},
  // {title: '选项-2', parent: "O"},
  // {title: '选项-2', parent: "O"},
  // {title: '选项-2', parent: "O"},
  // {title: '选项-2', parent: "O"},
  // {title: '选项-2', parent: "O"},
  // {title: '选项-2', parent: "O"},
  // {title: '选项-2', parent: "O"},
  // {title: '选项-2', parent: "O"},
  // {title: '选项-2', parent: "O"},
  {idf: 'P', title: 'P'},
  {title: '选项-2', parent: "P"},
  {title: '选项-2', parent: "P"},
  {title: '选项-2', parent: "P"},
  {title: '选项-2', parent: "P"},
  {title: '选项-2', parent: "P"},
  {title: '选项-2', parent: "P"},
  {title: '选项-2', parent: "P"},
  {title: '选项-2', parent: "P"},
  {title: '选项-2', parent: "P"},
  {title: '选项-2', parent: "P"},
  {title: '选项-2', parent: "P"},
  {title: '选项-2', parent: "P"},
  {idf: 'Q', title: 'Q'},
  {title: '选项-2', parent: "Q"},
  {title: '选项-2', parent: "Q"},
  {title: '选项-2', parent: "Q"},
  {title: '选项-2', parent: "Q"},
  {title: '选项-2', parent: "Q"},
  {title: '选项-2', parent: "Q"},
  {title: '选项-2', parent: "Q"},
  {title: '选项-2', parent: "Q"},
  {title: '选项-2', parent: "Q"},
  {title: '选项-2', parent: "Q"},
  {title: '选项-2', parent: "Q"},
  {title: '选项-2', parent: "Q"},
  {idf: 'R', title: 'R'},
  {title: '选项-2', parent: "R"},
  {title: '选项-2', parent: "R"},
  {title: '选项-2', parent: "R"},
  {title: '选项-2', parent: "R"},
  {title: '选项-2', parent: "R"},
  {title: '选项-2', parent: "R"},
  {title: '选项-2', parent: "R"},
  {title: '选项-2', parent: "R"},
  {title: '选项-2', parent: "R"},
  {title: '选项-2', parent: "R"},
  {title: '选项-2', parent: "R"},
  {title: '选项-2', parent: "R"},
  {idf: 'S', title: 'S'},
  {title: '选项-2', parent: "S"},
  {title: '选项-2', parent: "S"},
  {title: '选项-2', parent: "S"},
  {title: '选项-2', parent: "S"},
  {title: '选项-2', parent: "S"},
  {title: '选项-2', parent: "S"},
  {title: '选项-2', parent: "S"},
  {title: '选项-2', parent: "S"},
  {title: '选项-2', parent: "S"},
  {title: '选项-2', parent: "S"},
  {title: '选项-2', parent: "S"},
  {title: '选项-2', parent: "S"},
  {idf: 'T', title: 'T'},
  {title: '选项-2', parent: "T"},
  {title: '选项-2', parent: "T"},
  {title: '选项-2', parent: "T"},
  {title: '选项-2', parent: "T"},
  {title: '选项-2', parent: "T"},
  {title: '选项-2', parent: "T"},
  {title: '选项-2', parent: "T"},
  {title: '选项-2', parent: "T"},
  {title: '选项-2', parent: "T"},
  {title: '选项-2', parent: "T"},
  {title: '选项-2', parent: "T"},
  {title: '选项-2', parent: "T"},
  {idf: 'U', title: 'U'},
  {title: '选项-2', parent: "U"},
  {title: '选项-2', parent: "U"},
  {title: '选项-2', parent: "U"},
  {title: '选项-2', parent: "U"},
  {title: '选项-2', parent: "U"},
  {title: '选项-2', parent: "U"},
  {title: '选项-2', parent: "U"},
  {title: '选项-2', parent: "U"},
  {title: '选项-2', parent: "U"},
  {title: '选项-2', parent: "U"},
  {title: '选项-2', parent: "U"},
  {title: '选项-2', parent: "U"},
  {idf: 'V', title: 'V'},
  {title: '选项-2', parent: "V"},
  {title: '选项-2', parent: "V"},
  {title: '选项-2', parent: "V"},
  {title: '选项-2', parent: "V"},
  {title: '选项-2', parent: "V"},
  {title: '选项-2', parent: "V"},
  {title: '选项-2', parent: "V"},
  {title: '选项-2', parent: "V"},
  {title: '选项-2', parent: "V"},
  {title: '选项-2', parent: "V"},
  {title: '选项-2', parent: "V"},
  {title: '选项-2', parent: "V"},
  {idf: 'W', title: 'W'},
  {title: '选项-2', parent: "W"},
  {title: '选项-2', parent: "W"},
  {title: '选项-2', parent: "W"},
  {title: '选项-2', parent: "W"},
  {title: '选项-2', parent: "W"},
  {title: '选项-2', parent: "W"},
  {title: '选项-2', parent: "W"},
  {title: '选项-2', parent: "W"},
  {title: '选项-2', parent: "W"},
  {title: '选项-2', parent: "W"},
  {title: '选项-2', parent: "W"},
  {title: '选项-2', parent: "W"},
  {idf: 'X', title: 'X'},
  {title: '选项-2', parent: "X"},
  {title: '选项-2', parent: "X"},
  {title: '选项-2', parent: "X"},
  {title: '选项-2', parent: "X"},
  {title: '选项-2', parent: "X"},
  {title: '选项-2', parent: "X"},
  {title: '选项-2', parent: "X"},
  {title: '选项-2', parent: "X"},
  {title: '选项-2', parent: "X"},
  {title: '选项-2', parent: "X"},
  {title: '选项-2', parent: "X"},
  {title: '选项-2', parent: "X"},
  {idf: 'Y', title: 'Y'},
  {title: '选项-2', parent: "Y"},
  {title: '选项-2', parent: "Y"},
  {title: '选项-2', parent: "Y"},
  {title: '选项-2', parent: "Y"},
  {title: '选项-2', parent: "Y"},
  {title: '选项-2', parent: "Y"},
  {title: '选项-2', parent: "Y"},
  {title: '选项-2', parent: "Y"},
  {title: '选项-2', parent: "Y"},
  {title: '选项-2', parent: "Y"},
  {title: '选项-2', parent: "Y"},
  {title: '选项-2', parent: "Y"},
  {idf: 'Z', title: 'Z'},
  {title: '选项-4', parent: "Z"},
  {title: '选项-4', parent: "Z"},
  {title: '选项-4', parent: "Z"},
  {title: '选项-4', parent: "Z"},
  {title: '选项-4', parent: "Z"},
  {title: '选项-4', parent: "Z"},
  {title: '选项-4', parent: "Z"},
  {title: '选项-4', parent: "Z"},
  {title: '选项-4', parent: "Z"},
  {title: '选项-4', parent: "Z"},
  {title: '选项-4', parent: "Z"},
  {title: '选项-4', parent: "Z"},
]
Pager({
  data: {
    tabConfig: mkTab('aabbcc', mockData, {
      tap(e, param, inst){
        console.log('====== hhhh');
      },
      longpress(e, param, inst){
        console.log('====== 7777');
      }
    }),
  },
  onLoad(){
    wx.showLoading({
      title: '加载中',
    })
  },
  onReady(){
    setTimeout(function () {
      wx.hideLoading()
    }, 1000)
  }
})
